
export const LOAD_ANNOUNCEMENTS = 'LOAD_ANNOUNCEMENTS';
export const LOAD_ANNOUNCEMENT_DATA = 'LOAD_ANNOUNCEMENT_DATA';
export const ADD_ANNOUNCEMENT = 'ADD_ANNOUNCEMENT';
export const EDIT_ANNOUNCEMENT = 'EDIT_ANNOUNCEMENT';
export const SELECT_ANNOUNCEMENT = 'SELECT_ANNOUNCEMENT';
export const FILTER_ANNOUNCEMENTS = 'FILTER_ANNOUNCEMENTS';
export const REMOVE_ANNOUNCEMENT = 'REMOVE_ANNOUNCEMENT';

